spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  config:
    activate:
      on-profile: conteiner
  datasource:
    url: jdbc:postgresql://localhost:5432/park
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: sua_senha'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
